From bf704c0f30a23bbcdca37f5ca0ddf1a347096643 Mon Sep 17 00:00:00 2001
From: Stuart Archibald <stuart.archibald@googlemail.com>
Date: Tue, 1 May 2018 16:22:09 +0100
Subject: [PATCH] Fix encoding to 'UTF-8' in `check_output` decode.

As title.

Fixes #2924
---
 numba/tests/test_runtests.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/numba/tests/test_runtests.py b/numba/tests/test_runtests.py
index 4cdfc88a6..3e789b99e 100755
--- a/numba/tests/test_runtests.py
+++ b/numba/tests/test_runtests.py
@@ -14,7 +14,7 @@ class TestCase(unittest.TestCase):
 
     def get_testsuite_listing(self, args):
         cmd = ['python', '-m', 'numba.runtests', '-l'] + list(args)
-        lines = subprocess.check_output(cmd).decode().splitlines()
+        lines = subprocess.check_output(cmd).decode('UTF-8').splitlines()
         lines = [line for line in lines if line.strip()]
         return lines
 
@@ -54,7 +54,7 @@ def check_testsuite_size(self, args, minsize, maxsize=None):
                 msg = ("Test discovery has failed, the reported cause of the "
                        " failure is:\n\n:")
                 indented  = '\n'.join(['\t' + x for x in
-                                       e.output.decode().splitlines()])
+                                       e.output.decode('UTF-8').splitlines()])
                 raise RuntimeError(msg + indented)
         return lines
 
